import Logoutbtn from '@/components/Logout';
import Link from 'next/link';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>this is root layout</div>
        <section>{children}</section>
        <div>
          <Link href={"/"}>home</Link>
        </div>
        <div>
          <Link href={"/member"}>member</Link>
        </div>
        <div>
          <Link href={"/testServ"}>testServ</Link>
        </div>
        <Logoutbtn />
      </body>
    </html>
  );
}
