export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>this is root layout</div>
        <section>{children}</section>
      </body>
    </html>
  );
}
