import Logoutbtn from '@/components/Logout';
import { customInitApp } from '@/library/fb-admin-config';
import { auth } from 'firebase-admin';
import { cookies } from 'next/headers';
import Link from 'next/link';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  customInitApp();
  const cookieStore = cookies();
  const session = cookieStore.get("session")?.value;
  if (session) {
    // const decodedClaims = await auth().verifySessionCookie(session, true);
  }

  return (
    <html lang="en">
      <body>
        <div>this is root layout</div>
        <section>{children}</section>
        <div>
          <Link href={"/"}>home</Link>
        </div>
        <div>
          <Link href={"/member"}>member</Link>
        </div>
        <div>
          <Link href={"/testServ"}>testServ</Link>
        </div>
        <Logoutbtn />
      </body>
    </html>
  );
}
